Repository kiheyunkim/SimpleChatting, pull requests merged in 2021-08, with the labels that each got.

#4 [markup/CSE-SimpleChatting-#1]디자인 변경(html, css)
  public/css/index.css
  public/img/edit.png
  public/index.html
Labels: enhancement

#6 [KKH-SimpleChatting-#5] 내 닉네임 표시 및 수정 기능
  README.md
  Server.js
  function/nameChecker.js
  public/js/chatting.js
  screenshot/src3.PNG
Labels: documentation, enhancement

#7 닉네임 검색 기능 삭제 및 관련 파일 삭제
  public/css/index.css
  public/img/magnifying-glass.png
  public/img/send.png
  public/index.html
Labels: dependencies

#10 [SimpleChatting-#8] 빈칸 닉네임 입력시 경고창 출력
  public/js/chatting.js
Labels: bug

#11 README 수정 및 css 일부 수정
  README.md
  public/css/index.css
  screenshot/src1.PNG
  screenshot/src2.PNG
  screenshot/src3.PNG
  screenshot/src4.PNG
  screenshot/src5.PNG
  screenshot/src6.PNG
Labels: documentation, enhancement
